name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting yarah
        run: echo "Hello from printing!"
      - name: Print goodbye
        run: echo "Goodbye yarah"
